language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6

matrix:
  fast_finish: true

before_script:
    - sudo pecl install oauth
    - composer self-update
    - composer install

script:
    - composer test
